version: '3.8'

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    shm_size: "512m"
    ports:
      - "8971:5000"
    volumes:
      - /opt/frigate/config:/config
      - /opt/frigate/cache:/tmp/cache
    environment:
      - TZ=UTC
