version: '3.8'

services:
  squad44-server:
    image: cm2network/squad
    container_name: squad44-server
    restart: unless-stopped
    ports:
      - "10027:10027/udp"
      - "10037:10037/udp"
    environment:
      - PORT=10027
      - QUERYPORT=10037
      - PUID=1000
      - PGID=1000
      - STEAMAPPID=746200
      - STEAMAPPDIR=/home/steam/squad44-dedicated
    volumes:
      - squad44_data:/home/steam/squad44-dedicated

volumes:
  squad44_data:
