version: '3.8'

services:
  arrfiles:
    image: filebrowser/filebrowser:latest
    container_name: arrfiles
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8088:80"
    volumes:
      - /opt/arrfiles/config:/config
      - /opt/arrfiles/database:/database
      - /opt/media:/srv
    environment:
      - FB_BASEURL=/
      - TZ=UTC
