version: '3.8'

services:
  aoe2de-server:
    image: cm2network/steamcmd
    container_name: aoe2de-server
    restart: unless-stopped
    ports:
      - "27020:27015/udp"
      - "27021:27016/udp"
    command: [ "tail", "-f", "/dev/null" ] # Placeholder until a valid Wine image is found
    volumes:
      - aoe2de_data:/serverdata

volumes:
  aoe2de_data:
